"""Add phone_number to users

Revision ID: 8f9d8026a072
Revises: 2bdfdb1d7a9a
Create Date: 2024-12-16 16:37:31.409242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f9d8026a072'
down_revision: Union[str, None] = '2bdfdb1d7a9a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
