"""Add phone_number column to users

Revision ID: dec91eaeec42
Revises: 1034b9b12bc7
Create Date: 2024-12-16 16:15:34.710418

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dec91eaeec42'
down_revision: Union[str, None] = '1034b9b12bc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone_number', sa.String(), nullable=True))
    op.drop_column('users', 'phone number')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone number', sa.VARCHAR(), nullable=True))
    op.drop_column('users', 'phone_number')
    # ### end Alembic commands ###
